#BSUB -J mm_batch_gpu
#BSUB -o map_memcpy_%J.out
#BSUB -q hpcintrogpu
#BSUB -n 32
#BSUB -R "rusage[mem=2048]"
#BSUB -W 15
#BSUB -R "span[hosts=1]"
#BSUB -gpu "num=1:mode=exclusive_process"


module load nvhpc/24.11


# Loop over matrix sizes
for size in 100 200 300 400 500 600 700 800 
do
    # Run the map_memcpu_compare_batch.sh script
    echo "Size $size"
    ./poisson $size 1000 -1.0 10.0 0 0 1 1 0
done

# End of file