#BSUB -J norm_compare
#BSUB -o norm_compare_%J.out
#BSUB -q hpcintrogpu
#BSUB -n 32
#BSUB -R "rusage[mem=2048]"
#BSUB -W 15
#BSUB -R "span[hosts=1]"
#BSUB -gpu "num=1:mode=exclusive_process"


module load nvhpc/24.11

for i in 1 2 3 4 5
do
    echo "Round $i with stopping tolerance 1"
    OMP_NUM_THREADS=32 ./poisson 500 1000 1.0 10.0 0 1 0 1 0
    echo "Round $i without stopping tolerance" 
    OMP_NUM_THREADS=32 ./poisson 500 1000 -1.0 10.0 0 1 0 1 0 

done

# End of file